apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: bucket.sop.io
spec:
  defaultCompositionRef:
    name: bucket
  group: sop.io
  names:
    categories:
      - crossplane
      - sop
      - dkb
      - managed
      - pawel
    kind: bucket
    plural: bucket
  versions:
    - additionalPrinterColumns: []
      name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: >
                A Test Description
              properties:
                bucketName:
                  description: global uniq name for bucket
                  type: string
            status:
              description: >
                A Status represents the observed states
              properties:
                bucket:
                  description: >
                    Freeform field containing information about needed eks fields
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object