---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: docker.io/crossplanecontrib/provider-aws:v0.33.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: docker.io/crossplanecontrib/provider-kubernetes:v0.5.0
  controllerConfigRef:
    name: crossplane-provider-kubernetes
